mirage/ocaml-dns

- CHANGES
- lib/packet.ml
- lib/packet.mli
- lib/query.ml
- lib_test/ounit/test_packet.ml
- lib_test/ounit/test_query.ml
@dsheets Is this what you meant?
> Issue #41: try to make the unicast response a bit less confusing

- .travis-ci.sh
- README.md
this PR should fix the travis builds and adding travis link to README
> Fixing travis builds

- lwt/dns_server.ml
- lwt/dns_server.mli
I thought this function might be useful for other projects too
> adding process composition function to Dns_server

- lib_test/ounit/test.ml
- lib_test/ounit/test_dns_server_mirage.ml
- mirage/dns_server_mirage.ml
P.S. I am aware that mirage-net-pcap might simplify some of the DNS tests, but I haven't tried it yet
> Bug fix and unit test for issue #69

- lwt/dns_server_unix.ml
There is a regression in 0.15.2 that results in only the first DNS query being answered when using `Dns_server_unix.listen` (the loop [here](https://github.com/mirage/ocaml-dns/blob/master/lwt/dns_server_unix.ml#L81) is only called once). This PR should fix that.
> Answer more than one query in dns_server_unix.listen

- examples/forward.ml
Name.domain_name_to_string -> Name.to_string
> Small fix to update example to the new API

- lwt/dns_server_unix.ml
- opam
Lwt_unix.bind now returns a promise.
Rleated to ocsigen/lwt#308
> Update to lwt.3.0.0

- CHANGES.md
- Makefile
- async/async_dns_resolver.ml
- async/async_dns_resolver.mli
- async/async_dns_resolver_unix.ml
- async/async_dns_resolver_unix.mli
- lib/dig.ml
- lib/loader.ml
- lib/loader.mli
- lib/name.ml
- lib/operators.ml
- lib/resolvconf.ml
- lib/zone_lexer.mll
- lib_test/ounit/test_mdns_responder.ml
- lib_test/ounit/test_query.ml
- lwt-unix/dig_unix.ml
- lwt-unix/dns_resolver_unix.ml
- lwt-unix/dns_server_unix.ml
- lwt/dns_resolver.ml
- lwt/dns_server.ml
This doesnt make the repo warnings clean, but is a step in the right direction
> prepare 1.0.0 and fix many warnings

- async/async_dns_resolver_unix.ml
> close reader and writer properly to avoid raising exception unexpectedly

- lib/loader.ml
- lib/zone_lexer.mll
- lib/zone_parser.mly
- lib_test/ounit/test_name.ml
- lib_test/ounit/test_trie.ml
> Fix build with OCaml 4.06 (and with -safe-string)

- CHANGES.md
> Prepare to release v1.0.1

- .travis.yml
- mirage-dns.opam
- mirage/dns_server_mirage.ml
- mirage/dns_server_mirage.mli
- mirage/dune
> Use the new KV.RO API

- dns-certify.opam
- dns-cli.opam
- mirage/certify/dns_mirage_certify.ml
- mirage/certify/dns_mirage_certify.mli
(release pending merge into opam-repository at https://github.com/ocaml/opam-repository/pull/14659)
> adapt to x509 0.7.1 API

- cache/dns_cache.ml
- cache/dns_cache.mli
- client/dns_client.ml
- test/cache.ml
as suggested in https://github.com/mirage/mirage-nat/pull/28#issuecomment-482619504
also, reduced complexity (O(log n) -> O(1)) https://pqwy.github.io/lru/doc/lru/Lru/index.html
> Dns_cache: use mutable LRU instead of functional one

- app/ocertify.ml
- certify/dns_certify.ml
- certify/dns_certify.mli
- mirage/certify/dns_certify_mirage.ml
> Fix certificate signing requests, support multiple hostnames in ocertify

- CHANGES.md
all tests are passing, this has been deployed already ;)
> prepare 4.2.0

- server/dns_server.ml
- server/dns_server.mli
- src/dns.ml
- test/server.ml
see individual commit messages for details, this also adds a mode allowing unauthenticated zone transfers in the primary server (which @dinosaure had interest in).
> refactor and improve server authentication

- CHANGES.md
- server/dns_server.mli
- test/server.ml
update CHANGES for a new release
//cc @cfcs a review would be very welcome
> add tests for Authentication.access_granted and Authentication.zone_and_operation

- client/dns_client.ml
- client/dns_client.mli
- dns-stub.opam
- lwt/client/dns_client_lwt.ml
- mirage/client/dns_client_mirage.ml
- mirage/stub/dns_stub_mirage.ml
- unix/client/dns_client_unix.ml
> embed IP address of recursive resolver only once in dns_client

- client/dns_client.ml
handle localhost and invalid appropriately as 'Name Resolution APIs and Libraries'
more specifically, `*.localhost.` resolves to A 127.0.0.1 AAAA ::1, all other query types NXDomain
`*.invalid` resolves to a negative reply (NXDomain).
fixes #220 //cc @cfcs
> client: stick to RFC 6761 (special purpose domain names)

- app/ocertify.ml
- certify/dns_certify.ml
- certify/dns_certify.mli
- mirage/certify/dns_certify_mirage.ml
> certify: provide cert_matches_csr function that checks whether a certificate matches the CSR

- app/ocertify.ml
- src/dns.ml
- src/dns.mli
- zone/dns_zone_parser.mly
> introduce max_rdata_length and check all incoming values

- app/ocertify.ml
Since ACME v2 the full chain is available via ACME. ocertify.exe stores the
entire chain and leaf certificate in the pem file. Now, reading this pem file
lead to an error since only the leaf certificate was expected.
This commit reads a list of certificates from the file, and picks the one that
supports the hostname for further processing (validity checking, etc.).
> ocertify: support the pem file in use to contain a certificate chain

- mirage/resolver/dns_resolver_mirage.ml
- resolver/dns_resolver.ml
- resolver/dns_resolver.mli
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_cache.mli
> Resolver fixes

- app/dns_cli.ml
- app/onotify.ml
- app/oupdate.ml
- client/dns_client.ml
- dns-cli.opam
- dns-client.opam
- dns-mirage.opam
- dns-server.opam
- dns-stub.opam
- dns-tsig.opam
- dns.opam
- lwt/client/dns_client_lwt.ml
- mirage/dns_mirage.ml
- mirage/stub/dns_stub_mirage.ml
- server/dns_server.ml
- src/dns.ml
- test/server.ml
- tsig/dns_tsig.ml
- zone/dns_zone_parser.mly
> use Cstruct.length instead of deprecated Cstruct.len

- dns-certify.opam
- dns-client.opam
- dns-mirage.opam
- dns-resolver.opam
- dns-server.opam
- dns-stub.opam
- mirage/certify/dns_certify_mirage.ml
- mirage/certify/dns_certify_mirage.mli
- mirage/certify/dune
- mirage/client/dns_client_mirage.ml
- mirage/client/dns_client_mirage.mli
- mirage/client/dune
- mirage/dns_mirage.ml
- mirage/dns_mirage.mli
- mirage/dune
- mirage/resolver/dns_resolver_mirage.ml
- mirage/resolver/dns_resolver_mirage.mli
- mirage/resolver/dune
- mirage/server/dns_server_mirage.ml
- mirage/server/dns_server_mirage.mli
- mirage/server/dune
- mirage/stub/dns_stub_mirage.ml
- mirage/stub/dune
`sed s/Mirage_stack/Tcpip.Stack/gc`
`sed s/mirage-stack/tcpip/gc`
/cc @hannesm
> Upgrade to tcpip.7.0.0

- lwt/client/dns_client_lwt.ml
- mirage/client/dns_client_mirage.ml
When multiple DNS requests are issued, each of them attempts a connection to
the resolver (since the connection initialization is not tracked), leading to
multiple file descriptors being used and the fd/flow being set to one of the
connections. Instead, once a connection is attempted, establish a Lwt_condition
and wait in other promises until that is resolved before proceeding.
> dns-client (mirage/lwt): avoid connecting to resolver race

- cache/dns_cache.ml
- src/dns.ml
- src/dns.mli
> dns-cache: report size, capacity, and weight in the metrics

- dns-client.opam
- lwt/client/dns_client_lwt.ml
- mirage/client/dns_client_mirage.ml
goes well with https://github.com/roburio/happy-eyeballs/pull/30
> adapt to new happy eyeballs

- app/dune
- app/ocertify.ml
- app/onotify.ml
- app/oupdate.ml
- dns-cli.opam
- dns-client-lwt.opam
- dns-client-mirage.opam
- dns-server.opam
- dns-stub.opam
- lwt/client/dns_client_lwt.ml
- lwt/client/dune
- mirage/client/dune
- mirage/stub/dune
- test/server.ml
- unix/client/dns_client_unix.ml
- unix/client/dns_client_unix.mli
- unix/client/ohost.ml
this shaves some dependencies, but is a breaking change...
> split dns-client opam package into three: dns-client, dns-client-lwt, dns-client-mirage

- test/server.ml
- zone/dns_zone_lexer.mll
- zone/dns_zone_parser.mly
Since I'm a bit short on time, I wonder whether reverting #310 and cutting a release is the path forward. Or, @RyanGibb are you still using LOC records and interesting in them? If yes, would you mind to take a look at the lexer/parser issue and develop a fix (where this test case is passing)?
> A failing test case since #310 was merged

- dns-client-miou-unix.opam
- miou/client/dns_client_miou_unix.ml
- miou/client/dns_client_miou_unix.mli
- miou/client/dune
A free implementation of `dns-client` with Miou (and `happy-eyeballs-miou-unix`).
> Provide a Miou implementation of dns-client

- dnssec/dnssec.ml
see https://lists.dns-oarc.net/pipermail/dns-operations/2024-November/022711.html
> add ksk2024 

- cache/dns_cache.ml
- cache/dns_cache.mli
- dns-certify.opam
- dns-cli.opam
- dns-client-lwt.opam
- dns-client-miou-unix.opam
- dns-client-mirage.opam
- dns-client.opam
- dns-mirage.opam
- dns-resolver.opam
- dns-server.opam
- dns-stub.opam
- dns-tsig.opam
- dns.opam
- dnssec.opam
- dune-project
- resolver/dns_resolver.ml
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_cache.mli
- resolver/dune
- test/dune
- test/resolver.ml
- test/tsig.ml
also fix that test.
//cc @reynir -- still need to wrap my head around whether the API level is the right one...
> resolver: add a failing test when a loop is in the cache

- app/dns_cli.ml
- app/dune
- app/odnssec.ml
- app/resolver.ml
also, use a logs reporter with timestamp and source by default
> app/resolver: allow to adjust log level

- dnssec/dnssec.ml
- resolver/dns_resolver_cache.ml
this fixes the loop when querying for a name without DS/DNSKEY present. we can just avoid that query entirely.
/cc @reynir
> Fix resolver with DNSsec and no dnssec signatures present

- resolver/dns_resolver.ml
- resolver/dns_resolver.mli
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_cache.mli
- test/resolver.ml
preparation for being more agnostic about the transport... (though not using happy-eyeballs (yet?)) //cc @reynir
> dns_resolver: instead of querying one (ip, ns), query up to three

- resolver/dns_resolver.ml
> resolver: in the extended error, report the SOA hostmaster as filtering reason

- app/resolver.ml
- mirage/resolver/dns_resolver_mirage.ml
- resolver/dns_resolver.ml
- resolver/dns_resolver.mli
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_cache.mli
- test/resolver.ml
(qname minimisation, opportunistic TLS, dnssec)
> being able to enable/disable features in resolver
