mirage/ocaml-dns

- lib/loader.ml
- lib/loader.mli
- lib/name.ml
- lib/name.mli
- lib/packet.ml
- lib/query.ml
- lib/zone.ml
- lib/zone_parser.mly
- lib_test/unix/time_server.ml
- lwt/dns_server.ml
This is my attempt to no longer expose that domain_name is implemented as a string list in the Name module, please review
Discussion about making domain_name abstract: https://github.com/mirage/ocaml-dns/issues/51
> Making the type Name.domain_name abstract

- mirage/dns_resolver_mirage.ml
Avoid choosing source ports greater than 65535, as S.listen_udpv4 does not currently detect or fix the overflow (see https://github.com/mirage/mirage-tcpip/pull/167 ).
It's not clear to me what the original logic was intended to reflect (perhaps it used to be 65300 + 255?); if this fix is also wrong, I'm happy to change it.
> change source port randomization to avoid overflow

- lib/query.ml
Some DNS servers (e.g. the one in the Technicolor TG582n) will check this bit is unset and ignore packets if it is set.
This issue has been present since this function was written in 2012.
> Query.create: do not set AA on queries

- lib_test/ounit/test_mdns_resolver_mirage.ml
@yomimono this makes the tests compile (for some reason the Dns_resolver_unix::resolution-error test fails on my FreeBSD)
> stub implement pseudoheader, now required by mirage-types

- lib_test/ounit/test_mdns_resolver_mirage.ml
These changes are needed to preserve compatibility with `mirage-types` once https://github.com/mirage/mirage/pull/643 is merged.
> remove dummied-out mode from test stack configuration

- lib_test/ounit/test_mdns_resolver_mirage.ml
- mirage/dns_resolver_mirage.ml
- mirage/dns_server_mirage.ml
- mirage/mdns_resolver_mirage.ml
This PR causes `dns` to build proposed upstream Mirage 3 API changes, but will break backward compatibility with the current released mirage package set. See mirage/mirage#690 for details on the upstream changes to the API.
> compatibility with upstream UDP API changes (result types)

- opam
fixes e.g. https://travis-ci.org/mirage/ocaml-git/jobs/183991365
> require mirage-types-lwt instead of mirage-types (V1_LWT is used)

- lib_test/ounit/test_mdns_resolver_mirage.ml
See #122 , but these could probably be replaced entirely by mirage-vnetif as noted in #106.
> remove non-explanatory comments in mdns_resolver_mirage

- lib/packet.ml
- lib_test/ounit/test_packet.ml
Previously if we parsed a list of resource records which looked like this in the packet:
;; ANSWER SECTION:
download.camlcity.org.	299	IN	CNAME	cx30.rm.camlcity.org.
cx30.rm.camlcity.org.	299	IN	A	138.201.190.144
We would get a list which `marshal` would convert into this:
;; ANSWER SECTION:
cx30.rm.camlcity.org.	299	IN	A	138.201.190.144
download.camlcity.org.	299	IN	CNAME	cx30.rm.camlcity.org.
Unfortunately some resolvers will reject this response. This was noticed by downloading findlib-1.6.2 in an Ubuntu-12.04 container using an ocaml-dns-derived DNS forwarder.
In general I think we should aim to make `parse ( marshal x ) = x`
This patch adjusts the test cases to match, since they were doing `List.rev` themselves after calling `parse`.
> parse: don't reverse the order of resource records in the parser

- CHANGES.md
Previously a v0.19.1 release was started but never tagged. Let's
try again but including the DNS parsing pointer to pointer fix.
> Prepare to release v0.19.1 again

- CHANGES.md
- _tags
- opam
This seems to have been pulled in implicitly before, but breaks
when compiled with jbuilder
> zone_parser: explictly depend on uri.services

- examples/Makefile
- examples/server.ml
This is a basic server which has a static lookup table. It doesn't
use the Trie for simplicity. It mainly shows the types needed to
get from a request to a response.
> examples: add another really simple example

- lwt-unix/jbuild
> Move command line parser from dns-lwt-unix to an executable.

- dns-async.opam
- dns-lwt-unix.opam
- dns-lwt.opam
- dns.opam
- mirage-dns.opam
Pinning to --dev-repo currently fails, since jbuilder (1.0+beta20) cannot determine the package name.  An example error from opam 2.0.0~rc:
```
#=== ERROR while compiling dns-lwt-unix.1.0.1 =================================#
```
> Pass package names to jbuilder subst.

- lib/name.ml
- lib/packet.ml
- lib/packet.mli
- lib/probe.ml
- lib_test/ounit/test_name.ml
Domain name labels can be either be empty (root), text labels or pointers. The first two bits help to distinguish text labels from pointers : text labels start with two 0 bits (e.g. 0b0_00000001), whereas pointers start with two 1 bits (e.g. 0b0_11000001). That means, any label starting with 10 or 01 is invalid.
However, the parsing function in name.ml did it wrong when checking for pointers. It only checks if one of the two first bits are 1 to assume it's a pointer :
`let v = 0b0_10000001 in (v land 0b0_11000000) != 0` returns `true` even though v isn't a pointer.
A solution would be to replace 
`(v land 0b0_11000000) != 0` 
with 
`(v land 0b0_11000000) == 0b0_11000000`.
Another solution could be `v >= 0b0_11000000`.
> Correction on parsing function : pattern matching is not correct, total length is not checked

- .travis.yml
- CHANGES.md
- async/async_dns_resolver_unix.mli
- dns.opam
- lib/name.ml
- lib_test/ounit/dune
- lib_test/ounit/test_packet.ml
This is just the minimal changes to cut a point release of 1.1.3 so that we remove an upper bound on domain-name (and unblock ipaddr.4.0.0)
> [1.1 branch] Domain name 0.3.0 support

- app/dns_cli.ml
- app/ocertify.ml
- mirage/server/dns_mirage_server.ml
- mirage/server/dns_mirage_server.mli
- server/dns_server.ml
- server/dns_server.mli
this has been on some branch for a while, the primary server now contains a function to update the keys. Upon a key update, various janitoring is done (potentially notifications are generated (when new keys are added), other notifications are dropped (when keys are removed)).
This functionality is not exposed via `nsupdate` (which was the case in an earlier no longer existing incarnation of uDNS -- with various `_key-management` keys -- a bad idea to transmit secrets in the clear via the wire), but via API. In deployments I use this to dynamically update the keys from a zone file stored in a git remote (to which someone pushes, and the unikernel pulls after getting notified).
two other commits in this PR:
- do not _require_ a DNS key in ocertify -- there are valid uses that only download …
> provide dynamic update of HMAC / TSIG keys

- client/dns_client_flow.ml
- client/dns_client_flow.mli
- lwt/client/dns_client_lwt.ml
- lwt/client/dns_client_lwt.mli
- mirage/client/dns_mirage_client.ml
- mirage/client/dns_mirage_client.mli
- unix/client/dns_client_unix.ml
- unix/client/dns_client_unix.mli
Dns_client_flow: require "close : flow -> unit io" to close a flow
Dns_*client*: provide close, and close on error to avoid file descriptor leaks
this is meant as alternative to #181
> Dns_client: revise "io" type (be polymorphic only in 'a, not in ('a, 'b))

- client/dns_client.ml
- client/dns_client.mli
- client/dns_client_flow.ml
- client/dns_client_flow.mli
- dns-mirage-client.opam
- lwt/client/dns_client_lwt.ml
- mirage/client/dns_mirage_client.ml
- mirage/client/dns_mirage_client.mli
- mirage/client/dune
- unix/client/dns_client_unix.ml
this is a solution for #165 -- another could be to fully functorize over Mirage_random.C (but that'd bring us a Mirage_random dependency in the pure client, which I'd avoid) -- let me know what you think about this! :)
> client: use Randomconv.int16, provide rng via create

- dns-server.opam
- mirage/dns_mirage.ml
- mirage/dns_mirage.mli
- mirage/server/dns_mirage_server.ml
- server/dns_server.ml
- server/dns_server.mli
- test/dune
- test/server.ml
we used to accumulate hacks and further maps and workaround just to ensure that "to each IP address, establish a single connection" -- esp. at startup of the primary (where it may want to inform a single IP about 100 zones; or when it received a signed SOA request (with a root key) for the root zone, replying with NOTIFY for all authoritative zones) and secondary (where it may want to request the SOA of a single primary for multiple zones). now, instead of having the result `(ip * cstruct.t) list`, using `(ip * cstruct.t list) list` allows the effectful layer to send all the notify/requests to that single ip address at once! (i.e. no fold and establish connections necessary :)
similarly, the secondary API got slightly revised, turns out `handle_*` may only ever result in _one_ reply and …
> server outgoing signature changes

- dns.opam
This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.
> opam: remove the 'build' directive on dune dependency

- dns-server.opam
- mirage/dns_mirage.ml
- mirage/server/dns_server_mirage.ml
- mirage/server/dune
at some point, the `counter_metrics` should be provided elsewhere (in metrics itself?), but for now this should be fine. //cc @cfcs
> provide statistics in dns-server.mirage

- src/dns.ml
- test/tests.ml
This follows RFC 2181 section 11 closely (and unbreaks regression4)!
> The DNS itself places only one restriction on the particular labels that can
> be used to identify resource records.  That one restriction relates to the
> length of the label and the full name.
> Dns: relax parsing of names: allow non-hostnames for all RR types

- README.md
- mirage/server/dns_server_mirage.ml
- mirage/server/dns_server_mirage.mli
- server/dns_server.ml
- server/dns_server.mli
- server/dns_trie.ml
- test/server.ml
Dns_mirage_server.primary: include above key name and source IP in on_update
this is mostly useful for a primary server with a git backend to create sensible commit messages
/cc @cfcs
> Dns_server.handle_buf: expose (optional) key name used to authenticate an update

- dune-project
The `menhir 2.0` extension for dune was introduced in dune 1.4 (see https://github.com/ocaml/dune/pull/863). Trying to use dune 1.2 or 1.3 on this project will result in an error.
This PR readjusts the constraints on dune to avoid such problem.
(discussed in https://github.com/ocaml/opam-repository/pull/15646)
(related to https://github.com/ocaml/dune/issues/2957)
> Remove unused dune extension

- mirage/server/dns_server_mirage.ml
- server/dns_server.ml
- server/dns_server.mli
- server/dune
- src/dns.mli
- test/server.ml
this adds more tests, esp. for the case a server has multiple zones and only one is updated. in 4.3.0 this lead to SOA serial bumps of all zones the primary is serving.
another test is a single nsupdate which updates multiple zones at once.
in dns server, also expose some counter metrics about received and transmitted dns packets
> server bugfix (in update); metrics

- server/dns_server.ml
- server/dns_trie.ml
- test/server.ml
this strengthens the `lookup` function (to return `` `NotAuthoritative`` more often), and relaxes the `Notification.secondaries` to also find glue records in the trie. This addresses (with some further changes to the primary-git unikernel #213)
also add tests for lookup in a trie where the zone does not contain a SOA record (glue-only), `lookup_glue` returns the resource record set
//cc @cfcs @dinosaure
> Find secondaries

- src/dns.ml
- src/dns.mli
The argument processing of [cmdliner](https://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALconv) works with a parser (``string -> ('a, [ `Msg of string ]) result``) and a pretty-printer (`'a Fmt.t`). Now, Dnskey.name_key_of_string provides the latter (and is used by a bunch of unikernels), while there's no `pp` for that pair. For convenience, the pretty-printer should be included. (see e.g. https://github.com/mmaker/ocaml-letsencrypt/blob/bfe9982cb21f56cbe3b13f9f5291d0ba37daf7d9/bin/oacmel.ml#L103-L109 or https://github.com/roburio/unikernels/blob/5ef50400420e66e9cfb7f96ec7c6258e0944328b/secondary/config.ml#L5-L7 (further processed in https://github.com/roburio/unikernels/blob/5ef50400420e66e9cfb7f96ec7c6258e0944328b/secondary/unikernel.ml#L6-L11)) where this may be useful.
> dns: provide Dnskey.pp_name_key (best used with Cmdliner)

- CHANGES.md
- app/dune
- app/ocertify.ml
- certify/dns_certify.ml
- certify/dns_certify.mli
- certify/dune
- dns-certify.opam
- dns-cli.opam
- dns-server.opam
- dns-tsig.opam
- mirage/certify/dns_certify_mirage.ml
- mirage/certify/dns_certify_mirage.mli
- mirage/certify/dune
- test/dune
- test/server.ml
- test/tsig.ml
- tsig/dns_tsig.ml
- tsig/dune
the main change is that let's encrypt now very conveniently provides the chain of trust as well as the end-entity certificate. this means that we no longer need to carry the hard-coded certificate around. but this implies that we need to store the CA chain somewhere (again, as TLSA records :)
I'm still not entirely happy with the dns_certify API, but I think this is moving into the right direction.
> revise dns_certify with new ACME / let's encrypt in mind

- CHANGES.md
- app/odns.ml
- client/dns_client.ml
- client/dns_client.mli
- dns-client.opam
- lwt/client/dns_client_lwt.ml
- lwt/client/dns_client_lwt.mli
- lwt/client/dune
- mirage/client/dns_client_mirage.ml
- mirage/client/dns_client_mirage.mli
- mirage/client/dune
- mirage/stub/dns_stub_mirage.ml
- test/client.ml
- unix/client/dns_client_unix.ml
- unix/client/dns_client_unix.mli
- unix/client/dune
- unix/client/ohost.ml
our goal was to have connect and request timeouts for the DNS client.
On the Unix backend, we only have request timeouts (since there's no socket option to set connect timeouts, and we didn't want to use `select`).
On Lwt, we can't use the `SO_RCVTIMEO` socket option since it results in EAGAIN which is handled by Lwt (which re-queues the event). Thus we use a Lwt.pick there (same on MirageOS).
> add timeout for dns-client

- mirage/server/dns_server_mirage.ml
- server/dns_server.ml
- server/dns_server.mli
- src/dns.ml
- src/dns.mli
- test/server.ml
this PR is two-fold:
- the first commit fixes an issue of DNS name compression: the pointer tag is 2 bit, and the pointer value is 14 bit -> any offset above (2 ^ 14) - 1 cannot be addressed. I encountered this when testing AXFR
- AXFR used to be limited (in dns_server) to TCP to avoid potential reordering and multiple packets issues. turns out, when storing more data in DNS, (2 ^ 16) - 1 bytes are not sufficient. the second commit adapts a new strategy for encoding AXFR replies: use multiple buffers (instead of setting the truncation bit) and leave sufficient space for tsig
- the third commit properly decodes those partial AXFR replies and handles them in the secondary NS.
that's unlikely the last word when it comes to AXFR:
- other implementations may leave out the question in the …
> Axfr fixes

- .travis.yml
- app/dune
- app/odns.ml
- app/onotify.ml
- app/oupdate.ml
- dns-cli.opam
- lwt/client/dns_client_lwt.ml
- lwt/client/dns_client_lwt.mli
- unix/client/dns_client_unix.ml
- unix/client/ohost.ml
The application may use Lwt, which allows entropy collection
> client: avoid initialization of RNG in library, move to appplications

- src/dns.ml
- src/dns.mli
- zone/dns_zone_parser.mly
the only check is that they must fit into the bit-size, but it is a bad idea
(future-proof-wise) to forbid any new algorithms.
The value checks now boil down to:
- Dnskey proto being 3
- CAA tag length > 0 && < 16
> DNS: relax which algorithm etc. types are accepted, extend variants with Unknown of int

- app/dune
- app/odns.ml
- dns-client.opam
- lwt/client/dns_client_lwt.ml
- lwt/client/dns_client_lwt.mli
- lwt/client/dune
- unix/client/dns_client_unix.ml
- unix/client/dns_client_unix.mli
now that the lwt initialize is not in the lwt event loop, and also safe to be called multiple times (only the first call will do any work), it is good to call in the library code on top level.
> client: initialize RNG in library code

- CHANGES.md
- server/dns_server.ml
manually verified that the new behaviour is as desired in RFC 6891 (ref dns flag day)
> dns server: improve error reporting of incoming packets (fixes #166)

- app/dns_cli.ml
otherwise keys with `_notify` are not accepted (e.g. by onotify.exe).
> accept notify keys in namekey_c as well

- lwt/client/dns_client_lwt.ml
- lwt/client/dune
- unix/client/dns_client_unix.ml
- unix/client/dune
this changes the default behaviour by using the system-configured nameserver(s).
there are some issues with this strategy:
- the system-configured nameserver may be UDP only, in which case the client will fail
- the first nameserver may be unreachable
> client (unix, lwt): in "create" parse /etc/resolv.conf and use first IPv4 address of a nameserver

- src/dns.ml
- test/tests.ml
- zone/dns_zone_parser.mly
Previously, each TXT record hold a single string up to 255 characters in length.
When the length was exceeded, a new resource record was used. This is wasteful
(name, type, class, len needs to be repeated) and unexpected in some cases
(the requesting party gets multiple resource records which content needs to be
concatenated). The Txt.encode and Txt.decode did not behave in the same way
(decode split individual character strings, encode encoded only a single one).
When I tried to introduce some DKIM keys into my domains, I hit this issue that
DKIM check tools couldn't handle the responses from my servers. With this change
(and regression test):
(a) the Txt record can hold values that exceed 255 bytes
(b) in Txt.decode, a single resource record is a single entry in the map (the
charstrings …
> DNS: revise TXT resource record encoding and storage

- mirage/certify/dns_certify_mirage.ml
previously, all additional hostnames needed to be present in there as well.
this is not needed: the CSR to be uploaded is only for the zone of hostname
(the let's encrypt thingy needs to ensure that it can access all zones in the
CSR)
> dns-certify-mirage: only require dnskey to be valid for hostname

- src/dns.ml
- src/dns.mli
- test/tests.ml
Previously, tsig carrying an error with a second timestamp in "other" attempted
to decode at a wrong offset. Now, the correct offset is used, and the ptime
construction is hardened.
Adds a regression test, which requires Dns.Packet.create to expose its ?tsig
argument.
> Fix decoding of tsig resource records

- app/ocertify.ml
- certify/dns_certify.mli
- dns-certify.opam
- dns-client.opam
- dns-mirage.opam
- dns-server.opam
- dns-stub.opam
- mirage/certify/dns_certify_mirage.ml
- mirage/certify/dns_certify_mirage.mli
- mirage/certify/dune
- mirage/client/dns_client_mirage.ml
- mirage/client/dns_client_mirage.mli
- mirage/dns_mirage.ml
- mirage/dns_mirage.mli
- mirage/resolver/dns_resolver_mirage.ml
- mirage/resolver/dns_resolver_mirage.mli
- mirage/server/dns_server_mirage.ml
- mirage/server/dns_server_mirage.mli
- mirage/stub/dns_stub_mirage.ml
- resolver/dns_resolver.ml
- resolver/dns_resolver.mli
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_cache.mli
- server/dns_server.ml
- server/dns_server.mli
- test/server.ml
this includes improvements for dns-certify:
- allow ``[`raw] Domain_name.t`` for additional hostnames
- avoid dependency on tls, return `X509.Certificate.t list * Mirage_crypto_pk.RSA.priv` instead of `Tls.Config.own_cert` (makes this more composable as well)
- rebased dual stack patches from #239
> dns-certify improvements and dual stack support

- app/dns_cli.ml
- app/ocertify.ml
- app/odns.ml
- app/onotify.ml
- app/oupdate.ml
- certify/dns_certify.ml
- certify/dns_certify.mli
- certify/dune
- client/dns_client.ml
- client/dns_client.mli
- dns-certify.opam
- dns-cli.opam
- dns-client.opam
- dns-mirage.opam
- dns-resolver.opam
- dns-server.opam
- dns-stub.opam
- dns-tsig.opam
- dns.opam
- lwt/client/dns_client_lwt.ml
- lwt/client/dns_client_lwt.mli
- mirage/certify/dns_certify_mirage.ml
- mirage/certify/dns_certify_mirage.mli
- mirage/client/dns_client_mirage.ml
- mirage/stub/dns_stub_mirage.ml
- server/dns_server.ml
- unix/client/dns_client_unix.ml
- unix/client/dns_client_unix.mli
(a) dns-certify supports more key types than RSA
(b) IPv6 support in dns-client.unix & dns-client.lwt
(c) further tweaks
> API updates

- cache/dns_cache.ml
- cache/dns_cache.mli
- client/dns_client.ml
- resolver/dns_resolver.ml
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_cache.mli
- resolver/dns_resolver_utils.ml
- resolver/dns_resolver_utils.mli
- resolver/dune
- test/cache.ml
- test/resolver.ml
- use a LRU.F (to cut down on memory usage) instead of LRU.M
- provide Dns_cache.get_or_cname
- use Dns_cache in Dns_resolver (instead of Dns_resolver_cache)
> revise cache

- resolver/dns_resolver.ml
- resolver/dns_resolver.mli
- resolver/dns_resolver_utils.ml
- resolver/dns_resolver_utils.mli
A stub resolver is still available as dns-stub. This simplifies the resolver code.
> resolver: remove "mode" - which defaults to `Recursive

- cache/dns_cache.ml
- resolver/dns_resolver_cache.ml
- src/dns.ml
- src/dns.mli
- zone/dns_zone_parser.mly
This also renames "get_ttl" to "ttl".
//cc @reynir
> Dns: revise Rr_map.get_ttl and with_ttl to take 'a key -> 'a instead of b

- lwt/client/dns_client_lwt.ml
- unix/client/dns_client_unix.ml
Only affects lwt and unix.
Previously, when you started an application, /etc/resolv.conf was read once at
startup. When you switch to a different network, and /etc/resolv.conf is updated
by DHCP, this is not reflected in the dns-client.
Now, the digest of /etc/resolv.conf is stored internally, and if it changes, it
is parsed again. The lwt implementation needed to be modified slightly since
connect_to_ns_via_tcp carried a nameserver list, and a different task may have
been woken up. Now, there are two functions and it should play out nicely.
//cc @reynir addresses #243
> dns-client: if /etc/resolv.conf modifies, update the internal list of resolvers

- mirage/client/dns_client_mirage.ml
> Dns_client_mirage: allow hostname in authenticator

- dns-certify.opam
- mirage/certify/dns_certify_mirage.ml
the only semantic difference is when neither "key_data" nor "key_seed" is provided, in which case we error out now.
I think that's fine (I checked all cloned unikernels on my hard drive), but am happy to hear other thoughts.
> dns-certify-mirage: use X509.Private_key.of_string

- lwt/client/dns_client_lwt.ml
- mirage/client/dns_client_mirage.ml
If we don't have any pending requests we don't care much if the server closes the connection.
> Quieter logs

- test/server.ml
- zone/dns_zone.ml
Previously, a zone file that misses a final EOL before EOF would not be parsed correctly.
> Dns_zone: add a newline to buffer if there's none.

- resolvconf/dns_resolvconf.ml
- resolvconf/dune
- resolvconf/resolvconf_lexer.mll
- resolvconf/resolvconf_parser.mly
- resolvconf/resolvconf_state.ml
- test/resolvconf.ml
Inspired by the bug report in #328 by @bikallem, test case taken from there
@bikallem please let me know what you think of this PR, thanks.
> Resolv.conf parser: allow zone idx (RFC 4007) be present for IPv6 addresses

- dns-client-lwt.opam
Given `dns {= version}` is already there, this doesn't change the behaviour at all but simply makes it clearer
> Minor correction of the dependency constraints

- CHANGES.md
- server/dns_server.ml
> use the right key for the secondary and their zone transfers

- server/dns_trie.ml
- src/dns.ml
- src/dns.mli
See https://www.rfc-editor.org/rfc/rfc1035#section-3.3.10
Adds a dependency on `hex` to `dns` for pretty printing hex
> add NULL record

- resolver/dns_resolver.ml
- resolver/dns_resolver_cache.ml
- resolver/dns_resolver_utils.ml
- zone/dns_zone.ml
Dear developpers, the goal for this PR is to print a more specific message in the logs when the library (e.g. so far it prints `DBG [application]` sometimes and `DBG [more-specific]` othertimes, now it always provide the source module in the logs).
I just kept `app/*` with `Logs.*` as it will be displayed as `[application]` and it seems fine.
> be consistent in the use of Logs vs Log module

- mirage/server/dns_server_mirage.ml
If there's a (Dns_server.Secondary.)timer-triggered connection request, do not infinitely try to connect (via request -> fail -> close -> request) in a tight loop, but cancel on first sight (the timer is responsible for re-connecting)
I'm in the process of testing this in production.
> secondary server, mirage layer

- server/dns_server.mli
For out-of-band updates with the same semantics as DNS UPDATE. I've experimenting with a [capnproto interface](https://github.com/RyanGibb/eon/blob/839747770685f3553899df40ad799d6bb139803e/lib/cap/schema.capnp#L62) that [uses](https://github.com/RyanGibb/eon/blob/839747770685f3553899df40ad799d6bb139803e/lib/cap/domain.ml#L339) this function.
> expose Dns_server.update_data

- app/odns.ml
- app/odnssec.ml
- client/dns_client.ml
- client/dns_client.mli
- dns-client-lwt.opam
- dns-client-mirage.opam
- lwt/client/dns_client_lwt.ml
- lwt/client/dns_client_lwt.mli
- lwt/client/dune
- mirage/client/dns_client_mirage.ml
- mirage/client/dns_client_mirage.mli
- mirage/client/dune
- mirage/stub/dns_stub_mirage.ml
This commit delete a dependency cycle between happy-eyeballs, happy-eyeballs-lwt, dns and dns-client-lwt. The basic happy-eyeballs-lwt implementation is not able yet to resolve domain-name but the user can inject a getaddrinfo which may come from dns-client-lwt. The idea is: 1) create a happy-eyeballs-lwt instance
2) create a dns-client-lwt instance
3) inject Dns_client_lwt.getaddrinfo into our happy-eyeballs-lwt
instance
This patch delete a duplicate code about happy-eyeballs implementations.
Related to robur-coop/happy-eyeballs#38
> Directly use Happy_eyeballs_lwt instead of a copy of it

- miou/client/dns_client_miou_unix.ml
I checked the other implementations and they use the right `get_uint16`.
> Use String.get_uint_16 instead of get_int_16 which leads to a bad id for the packet

- mirage/certify/dns_certify_mirage.ml
- mirage/certify/dns_certify_mirage.mli
- src/dns.ml
- src/dns.mli
- test/tests.ml
These are the dual of of_string and name_key_of_string. Fixes #355
//cc @dinosaure
> Provide Dns.Dnskey.to_string and Dns.Dnskey.name_key_to_string

- mirage/certify/dns_certify_mirage.ml
- mirage/certify/dns_certify_mirage.mli
The reason is that the Dns.Dnskey.name_key_of_string return exactly that pair, and user code then looks nice :)
> dns_certify_mirage: use a pair instead of two separate arguments for the dns-key

- src/dns.ml
The elements were not always separated when printing.
Before this patch I would see something like:
ns3.google.com. 172800  AAAA    2001:4860:4802:36::ans4.google.com. 172800  A       216.239.38.10
where the more readable output is;
ns3.google.com. 172800  AAAA    2001:4860:4802:36::a
ns4.google.com. 172800  A       216.239.38.10
> Fix Dns.Name_rr_map.pp

- src/dns.ml
There's a tab character missing when printing a DNSKEY.
> Minor: fix printing of DNSKEY

- app/odnssec.ml
- dnssec/dnssec.ml
- resolver/dns_resolver.ml
- src/dns.ml
- src/dns.mli
- test/test_dnssec.ml
~~it's not yet used anywhere, so a bit boring... ;)~~
but we can use this now e.g. for dnssec validation (and better errors) \o/
it is now used in dnssec :)
> DNS: support for Extended DNS error (RFC 8914)

- mirage/resolver/dns_resolver_mirage.ml
- mirage/resolver/dns_resolver_mirage.mli
- resolver/dns_resolver.ml
- resolver/dns_resolver.mli
This allows us to dynamically update the DNS primary in Dns_mirage_resolver. 
**TODO:**
> dns-resolver: allow updates to the primary

- dns-certify.opam
- dns-cli.opam
- dns-client-lwt.opam
- dns-client-miou-unix.opam
- dns-client-mirage.opam
- dns-client.opam
- dns-mirage.opam
- dns-resolver.opam
- dns-server.opam
- dns-stub.opam
- dns-tsig.opam
- dns.opam
- dnssec.opam
- dune-project
- mirage/resolver/dns_resolver_mirage.mli
- mirage/resolver/dns_resolver_mirage_shared.mli
- mirage/resolver/dune
- mirage/stub/dns_stub_mirage.ml
- mirage/stub/dns_stub_mirage.mli
- mirage/stub/dune
- resolver/dns_block.ml
- resolver/dns_resolver.ml
- resolver/dns_resolver_metrics.ml
- resolver/dns_resolver_metrics.mli
- resolver/dune
This allows us to use the stub resolver in DNSvizor.
> Dns_stub: provide an interface, which is fairly similar to Dns_resolver_mirage
